### ISSUE TITLE
Issues about Pretrained DINO

### ISSUE THREAD

**Issue by RitchieAlpha** [chmxu/eTT_TMLR2022#6]
The DINO Pretrain used in this experiment is primary different from official dino by 1000 classes VS  712 classes?
And why do such a setting? It's clear that the main target of this paper is cross-domain application, so use full ImageNet dataset don't affect the result. Maybe this is for compare with other method like TSA and CTX? 
Looking forward to your reply! Thanks!

**Comment by chmxu** [comment]
Hi, technically speaking you can use the original 1000-class DINO weight for the experiments. We did not use this weight since we want to align our experiments with the previous methods, which only use meta-train set of ImageNet to train their model. Using whole training set of ImageNet to pretrain the model can obviously introduce extra knowledge to the model. Tab.7 in our paper shows that when using such a model, our method can have significant improvement on several dataset.
